# baseURL = "http://hira8.hira/"
baseURL = "https://www.hirano.cc/travel/bicycle"
languageCode = "ja-jp"
title = "Travels"
theme = "hira1"
# theme = "Blonde"
disablePathToLower = true

contentDir = "content/bicycle"

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
