name: Deploy travels


on:
  push:
    branches:
      - main
    paths:
        - ".github/workflows/travels.yaml"
        - "travels/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      # with:
      #   submodules: recursive

    # - name: hugo
    #   uses: klakegg/actions-hugo@1.0.0
    #   with:
    #     source: travels

    - name: setup tailwind
      run: |
        cd travels
        npm install

    - name: Build hugo
      run: |
        docker run -p 1313:1313 --rm -v `pwd`/travels:/src -e HUGO_ENV="production" -e NODE_ENV="production" peaceiris/hugo:latest-full

    - name: debug public
      run: ls -lR travels/public

    - name: create ssh.key
      run: |
        echo "${SSH_KEY}" > ssh.key
        chmod 400 ssh.key
      env:
        SSH_KEY:
          ${{ secrets.SSH_KEY_HIRANO_CC }}
    - name: rsync to hirano.cc
      run: |
        rsync -auzv --delete -e "ssh -p27 -i ssh.key -oStrictHostKeyChecking=no -oKexAlgorithms=+diffie-hellman-group-exchange-sha1" travels/public/ hirano@hirano.cc:/home/hirano/public_html/travel/bicycle/
